### ISSUE TITLE
Tareas--> Calendario: No tienen funcionalidad los botones para filtrar una búsqueda

### ISSUE THREAD

**Issue by aalfaro-trazalog** [Trazalog/traz-comp-tareasestandar#10]
**Descripción**: 
Todos los botones de filtrado, no  están funcionando. Si se selecciona un equipo o sector, no se actualiza la búsqueda, al igual que desde los buttons de Día, semana, mes y agenda. Independientemente de que se seleccione, la vista del calendario no se actualiza.

**Pasos para reproducir:**
1. En menú seleccionar Tareas y dar click en Planificación Tareas
2. Sobre el apartado de Pedidos Trabajo, dar click sobre alguno previamente creado (botón rectángular con ícono de user image)
3. Seleccionar un Hito
4. Seleccionar "Calendario" 
5. Click sobre botón del tipo de filtrado deseado (día, semana, mes, agenda)

https://user-images.githubusercontent.com/87376576/133801036-881fc9c3-bbc0-4e62-8a63-703407feb6e5.mp4

**Comment by floto-trazalog** [comment]
Falta solucionar detalles del Filtro por "Día" la vista muestra hasta las 17hs.

**Comment by floto-trazalog** [comment]
Se deja la issue del comment anterior: https://github.com/Trazalog/traz-comp-tareasestandar/issues/49
