### ISSUE TITLE
Tareas--> Asignar usuario: mostrar alerts y modal de confirmación cuando se reasigna

### ISSUE THREAD

**Issue by aalfaro-trazalog** [Trazalog/traz-comp-tareasestandar#13]
**Descripción:**

1. Cuando se asigna un usuario, la pantalla no muestra modal de confirmación, agregarlo.

2. Además es necesario agregar un alert que al seleccionar una tarea que ya tenía asignado un usuario, pregunte ¿Desea reasignar usuario? y que al presionar "Si" muestre un modal de confirmación. Además de que si la tarea ya ha sido tomada / iniciada por otro usuario, también muestre dicho estado. Lo del estado de la tarea se muestra en la issue #12 

https://user-images.githubusercontent.com/87376576/141853239-769578a3-f5b9-4305-920c-0481d0d35e47.mp4

**Pasos para reproducir:**

1. En Menú seleccionar "Tareas"
2. Seleccionar "Planificación de Tareas"
3. Seleccionar un Pedido de Trabajo y dar click en un hito asociado
4. Posicionarse en "Calendario" seleccionar una Tarea Planificada
5. Click en icono usuario

**Comment by floto-trazalog** [comment]
Solucionado en v2.1
