### ISSUE TITLE
Tareas--> Indicador Básico - Tareas

### ISSUE THREAD

**Issue by aalfaro-trazalog** [Trazalog/traz-comp-tareasestandar#19]
v 1.5.35

Descripción:

En el dashboard, crear indicadores de eficiencia, que comparen los valores del Porcentaje de tareas finalizadas a tiempo (fecha cumplida) vs el Porcentaje de tareas finalizadas fuera de tiempo (fecha excedida). 

Para determinar los porcentajes de las tareas es necesario contar con filtros que permitan seleccionar por usuario, equipo

https://www.canva.com/design/DAE3s8oVIOQ/30OLpvE2pzWHH136ijX8PQ/view?utm_content=DAE3s8oVIOQ&utm_campaign=designshare&utm_medium=link&utm_source=publishsharelink

Las comparaciones deben mostrarse en forma de gráfico de barras, junto con la referencia de que valor expresa cada color.

**Comment by floto-trazalog** [comment]
Solucionado en v2.1

Quedan mejoras por realizar pero la maqueta está desarrollada como se pide.
