### ISSUE TITLE
Tareas-->Planificación de tareas: no guarda nuevo Hito

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-comp-tareasestandar#22]
Ambiente Test. v1.5.36

**Descripción:**
Al clickear el botón "Guardar" para un nuevo Hito el sistema muestra la modal de carga pero no guarda el hito, correspondería que muestre un cartel avisando el fallo sino desconcierta al usuario

https://user-images.githubusercontent.com/88331456/153900266-7a133369-3859-45ca-ab04-d14c6992734b.mp4

**Pasos para reproducir:**  

1. En el menú dar click en Tareas
2. Dar click en Planificación de tareas
3. Dar click en Pedidos Trabajo
4. Dar click en "+Nuevo Hito"
5. Completar los datos obligatorios
6. Dar click en el botón "Adjuntar Archivo"
7. Seleccionar de las carpetas del dispositivo un archivo y click en "Abrir"
8. Dar click en el botón "Guardar"

**Comment by aalfaro-trazalog** [comment]
Nota v 2.0.3

Se puede crear un hito, pero el sistema sólo te permite hacerlo si se agrega un archivo adjunto. Esto es un Bug.
Revisar si el campo está tomado como obligatorio; en caso de que este configurado de esa manera, dejarlo como opcional.

**Comment by floto-trazalog** [comment]
Solucionado en v2.0.16
