### ISSUE TITLE
Planificación de Tareas: falta botón de minimizar el menú

### ISSUE THREAD

**Issue by aalfaro-trazalog** [Trazalog/traz-comp-tareasestandar#25]
v 1.5.37

Descripción:
Cuando seleccionamos el submódulo de planificación de tareas, la pantalla pierde el botón para contraer el menú.

![image](https://user-images.githubusercontent.com/87376576/154568926-5122aece-cbbf-4e90-a963-6da5a933227c.png)

**Comment by floto-trazalog** [comment]
Solucionado para v2.0.16
