### ISSUE TITLE
Planificación de Tareas: No puede crearse un nuevo hito

### ISSUE THREAD

**Issue by aalfaro-trazalog** [Trazalog/traz-comp-tareasestandar#4]
**Descripción:**
Al intentar crear un nuevo hito, no es posible seleccionar un Encargado. Por lo tanto no se puede guardar. 
//Probado en ambiente Yudica

**Pasos para reproducir:**

1. En menú seleccionar Tareas y dar click en Planificación Tareas
2. Sobre el apartado de Pedidos Trabajo, dar click sobre alguno previamente creado (botón rectangular con ícono de user image)
3. Click en botón "+ Nuevo Hito"
4. Completar los campos y dar click en "Guardar"

https://user-images.githubusercontent.com/87376576/132229065-696d1f19-6063-4ce1-b021-eca703094856.mp4

**Comment by floto-trazalog** [comment]
v0.2.3
Descripció: En Ambiente Test se repite exactamente el mismo bug al intentar crear nuevo Hito.

![CAP F15](https://user-images.githubusercontent.com/88331456/133504593-b284b838-f3f0-402f-8022-728845644487.gif)
