### ISSUE TITLE
Tareas-->Planificación de Tareas-->Pedidos Trabajo-->Hito: muestra un formulario de solo lectura 

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-comp-tareasestandar#58]
Ambiente test - v2.0.15.4.1

**Descripción**
Al presionar el botón Formulario Asociado el sistema muestra un formulario, pero no informa al usuario que es de solo lectura. Hoy, se completa y guarda este formulario desde la Bandeja de Tareas, al Tomar la tarea.
**Revisar con Mauricio y Amalia si es correcta esta funcionalidad o se debe poder guardar la información agregada.**

https://user-images.githubusercontent.com/88331456/175956144-75bcc9a8-e5aa-42c6-a47c-f03f4c9b719b.mp4

**Pasos a seguir**
1. Tareas
2. Clic en Planificación de tareas
3. Seleccionar un Pedido 
4. Seleccionar un Hito 
5. Clic en el botón "Formulario asociado"

**Comment by focafunk** [comment]
La funcionalidad orignal era que desde esta pantalla el Planificador de Tareas pueda revisar como se completo el formulario, es decir que sea de solo lectura. El que debe completar el formulario es el usuario al cual se le asignó la tarea.
