### ISSUE TITLE
Bandeja "Mis tareas"-->Tarea Planificada: botón sin funcionalidad & falla al guardar el formulario dinámico 

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-comp-tareasestandar#61]
Ambiente test - v2.0.15.4.1

**Descripción**
### 1)
Al iniciar la tarea se muestra en pantalla un ícono con forma de Clip, pero no tiene funcionalidad y tampoco, cartel. Se sugiere mostrar un cartel para que el usuario sepa qué hacer con él

![image](https://user-images.githubusercontent.com/88331456/175968510-2e9f1d20-7cbe-43e4-bed4-7bc312da2e1d.png)

### 2)
Al completar y guardar el formulario dinámico el sistema muestra un cartel de aprobación

![image](https://user-images.githubusercontent.com/88331456/175969509-9b873a10-b835-4cd5-9134-d5853d0ddfaa.png)

**Pasos a seguir**
1. Bandeja "Mis tareas"
2. Seleccionar una Tarea Planificada
3. Clic en el botón Tomar tarea
4. Clic en el botón Iniciar tarea

**Comment by focafunk** [comment]
Sobre 1), este bug esta relacionado con otro bug, en el cual en el ABM de Subtareas, si no seleccionamos un formulario (el cual no es obligatorio), auomaticamente me asigna un formulario ficticio, y por eso luego aparece el clip.
Sobre 2) Esto claramente esta mal, esa validación del formulario de calidad no debe estar en Taras, sino al momento de Finalizar Etapa, donde ahi se debe chequear si fue planificada para ese Lote un tarea de "Control de Calidad", la cual debe tener un formulario dinamico con algun item de tipo QC y si su respuesta fue negativa prohibir Finalizar la Etapa. Sacar de esta pantalla.

**Comment by floto-trazalog** [comment]
Solucionado en v2.0.18
