### ISSUE TITLE
Tareas--> Pedido de trabajo--> Agregar cabecera en ver detalle

### ISSUE THREAD

**Issue by aalfaro-trazalog** [Trazalog/traz-comp-tareasestandar#63]
v 2.0.16

Descripción:
Cuando se accede al detalle de un pedido de trabajo, el mismo **debe mostrar la cabecera desplegable con los datos del pedido.**
### Agregar dicha cabecera arriba de las pestañas de trazabilidad, comentarios, información y formulario, como se observa en la imagen

![image](https://user-images.githubusercontent.com/87376576/176914464-98899d59-59af-4846-8bfe-f5b82cc197a1.png)
-
-
-

Actualmente el sistema lo muestra así
![image](https://user-images.githubusercontent.com/87376576/176915236-a8d157e9-249c-4dcc-aa4e-a1852af0d335.png)

**Comment by floto-trazalog** [comment]
Solucionado en v2.1.10
