### ISSUE TITLE
Bandeja de tareas: cambiar color de la cabecera

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-comp-tareasestandar#70]
Ambiente test - v2.0.16

**Descripción**
Al seleccionar la tarea planificada cambiar el color de la cabecera del Pedido

![image](https://user-images.githubusercontent.com/88331456/177417039-897204fa-ae83-4429-8320-e5c2d0df4379.png)

**Comment by aalfaro-trazalog** [comment]
Desestimar
