### ISSUE TITLE
Bandeja de tareas: no se puede avanzar con el proceso de la Tarea planificada

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-comp-tareasestandar#72]
Ambiente test - v2.0.17

**Descripción**
### 1)
Al seleccionar la tarea planificada el sistema no recupera el formulario asociado a esta
### 2)
Al dar clic en la tarea el botón de "Tomar Tarea" el sistema no tiene funcionalidad

https://user-images.githubusercontent.com/88331456/179080634-3756cef6-a939-43f1-89be-9b1c53f5383a.mp4

**Comment by aalfaro-trazalog** [comment]
Solucionado en v2.1.5
