### ISSUE TITLE
Tareas--> Calendario: Equipo no muestra desplegable

### ISSUE THREAD

**Issue by aalfaro-trazalog** [Trazalog/traz-comp-tareasestandar#9]
Descripción:
Al seleccionar un Sector previamente cargado, y dar click en el desplegable de equipo, se muestra una raya negra. 

Sugerencia: Revisar si esto ocurre cuando un equipo no esta asociado a un sector.

Pasos para reproducir:

1. En menú seleccionar Tareas y dar click en Planificación Tareas
2. Sobre el apartado de Pedidos Trabajo, dar click sobre alguno previamente creado (botón rectángular con ícono de user image)
3. Seleccionar un Hito
4. Seleccionar "Calendario" y dar click en el desplegable "sector", seleccionar uno. 5. Seleccionar equipo 

![image](https://user-images.githubusercontent.com/87376576/133798327-2e3ac071-b685-408c-bbe1-a93c200c63cd.png)

**Comment by floto-trazalog** [comment]
Al tener en cuenta la **Sugerencia** y probar, sucede al seleccionar en el 4to paso el _Sector C_, no tiene Equipos cargados.

**Comment by floto-trazalog** [comment]
Se solucionará cuando se creen los formularios en el ABM Lista de valores
